### PR TITLE
TST: add Windows tests

### PR DESCRIPTION
**Pull request by hagenw**
Add test for Windows and update the package to make it Windows compatible.

### CODE REVIEW

**Comment by frankenjoe** [comment]
The coverage report only runs on `io.py` is that on purpose?

Or is it because `utils.py` is not completely covered. Because that we can simply solve if we exclude this https://github.com/audeering/audeer/blob/windows-tests/audeer/core/utils.py#L254 code block. It's anyway part of a deprecated method. Then we'd reach a `100%` code coverage.

**Comment by hagenw** [comment]
The coverage report in this pull request only runs on `io.py`, because the changes are only to this part.

In general you are right we are only at 97% overall coverage as I resisted from adding a test for the deprecated method. But yes, maybe we just mark that to be excluded from coverage. I will do it in a new pull request.

**Comment by frankenjoe** [comment]
Ok, should I merge with `Rebase and merge` as currently selected?

**Comment by hagenw** [comment]
Strange, I selected "Squash", don't know why this reverted?

Please go with squash.

**Pull request merged**
