### PR TITLE
DOC: add estimating pi example to usage

### PR DESCRIPTION
**Pull request by hagenw**
Would be nice to have an usage example inside the README.

### CODE REVIEW

**Comment by hagenw** [comment]
If you look at the 5 passed checks you will se that code coverage is now part of it.
If the code coverage would change by this pull request, it would also create automatically a comment stating what has changed.
I would propose that we start using it in that way and see how it goes. It also allows us to add a badge to the README, which I will do in another pull request.

**Comment by frankenjoe** [comment]
So far we had covered such examples in a usage section of the documentation. You think when we move packages on GitHub we should generally have also examples in the README?

**Comment by hagenw** [comment]
Yes, my idea is to have a short example  / catchy image at the README, which is also the start page of the documentation and a long usage section. We have it internally already for `audb`  this way. For `audeer` it is indeed a little bit strange, because the usage section is very short. Do you think we should not do it here, but move the new example also to the usage section?

**Comment by hagenw** [comment]
Or maybe we switch the two examples and move the very short one from the usage section to the README and the longer  one to the usage section?

**Comment by frankenjoe** [comment]
Yes, maybe we should switch. I like your new example, but I think it's a bit too complex as a starter.

**Comment by hagenw** [comment]
I switched the two examples now.

**Comment by frankenjoe** [comment]
I guess the reason you are not using `jupyter-sphinx` to run the usage example is that you don't want to introduce this dependency for only one example, right?

**Comment by hagenw** [comment]
Yes, and the other reason was that it cannot display the progress bar.

**Pull request merged**
